name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.0'
      - run: cd frontend && npm install
      - run: cd frontend && npm run relocate
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "django-auth-2022"
          heroku_email: "cavi4762@gmail.com"
          procfile: "web: cd backend && gunicorn backend.wsgi --log-file -"